export const defaulttasklist = {
    "geral":{

    },
    "folha": {
        "Cadastros e correções": true,
        "Mensalista": true,
        "Prolaborista": true,
        "Horista especial": false,
        "Criar verbas específicas": true,
        "Autônomo": false,
        "Empresa concomitante do SN": false,
        "Empresa PBM": false,
        "Empresa com departamentos": false,
        "Empresa com centros de custo": false,
        "Folha rateada entre tomadores": false,
        "Apuração de ponto": false,
        "Plano de saúde": false,
        "Cálculos": true,
        "Relatórios e recibos": true,
        "e-Social": true,
        "Auditor e-Social": true,
        "Módulo SST": false,
        "SChIp": true,
        "SEFIP e DARF IR": true,
        "Exportação para Sucessor": true,
        "Utilitários e opções de segurança": true,
    },
    "fiscal": {
        "Configurações declarações " : true,
        "Inconsistências" : true,
        "Plano de troca global" : true,
        "Plano de configurações do simples" : 1,
        "Planos estaduais " : true,
        "Schip fiscal" : true,
        "Importação de Notas Fiscais" : true,
        "Operações imobiliárias" : false,
        "Apuração dos impostos" : true,
        "Impostos e relatórios" : true,
        "Declarações" : true,
        "Auditor valores portais estaduais": false,
        "Auditor Connection IAT": false,
        "Auditor REINF": false,
    },
    "contábil": {
        "Configurações de contabilização"   : 1,
        "Plano de Contas"                   : 0.25,
        "Plano de Centro de Custo"          : 0.25,
        "Plano de/para"                     : 1,
        "Plano de Programas"                : 0.25,
        "Produtor Rural"                    : 1,
        "Carnê Leão"                        : 1,
        "IBGE"                              : 1,
        "Distribuição de Lucros"            : 0.25,
        "Lançamentos Automáticos SCHIP"     : 0.25,
        "Conciliações"                      : 0.25,
        "Importação de Saldos"              : 2,
        "Importação de Extratos"            : 0.25,
        "SPED ECD/ECF"                      : 1,
        "S-sfinge Tribunal de Contas SC"    : 0.25,
        "Relatórios"                        : 0.25,
        "Auditor ECD"                       : 0.5,
        "Auditor ECF"                       : 0.5,
        "NV Patrimônio"                     : 0.75,
        "NV Lalur"                          : 1.5,

},
    "financeiro": {
        "Central de Contas a Receber" : 0.5,
        "Central de Contas a Pagar" : 0.5,
        "Relatórios" : 0.5,
    },
    "tarefas": {
        "Plano tributário": 0.5,
        "Configuração de tarefas": 0.5,
        "Central de tarefas": 0.5,
        "Lançamentos de tarefas": 0.25,
        "Relatórios": 0.25,
    },
    "orcamentos": {
        
    },
    "protocolos": {
        "Consulta e emissão de protocolos" : 1,
    },
    "notificações": {
        "Configurações de usuários": 0.25,
        "Configuração de empresas":  0.25,
        "Detalhamento dos módulos":  0.25,
     },
     "impostos": {
        "Calculo geral de Impostos": 0.25,
        "Envio para SCI Report": 0.25,
        "Calculo de Juros e Multa Geral": 0.25,
        "Funcionalidades": 0.25,
    },
    "tecweb": {
        "Push SCI 2.0": 1,
        "Instalação Push": 1,
        "ISS Legal SCI": 1,
        "RH NET Social": 2,
        "Integra NET": 1,
        "SBS - Smart Bank Statement": 1.5,
        "SCI Report - Serviços 24H": 2,
        // "SCI Report - Tarefas": 1,
        "SCI Report - Atendimento": 0.5,
        "SCI Report - CND": 0.5,
        "Dasboard SCI": 1,
        "SCI Print PDF": 0.5,
        "Agente SCI": 0.5,
        "SCI App 4.0": 0.5,
    },
}