export const tasklist = {
    "folha": {
        "Cadastros e correções": 2,
        "Mensalista": 1,
        "Prolaborista": 0.5,
        "Horista especial": 1,
        "Criar verbas específicas": 1,
        "Autônomo": 0.5,
        "Empresa concomitante do SN": 1,
        "Empresa PBM": 0.5,
        "Empresa com departamentos": 0.5,
        "Empresa com centros de custo": 0.5,
        "Folha rateada entre tomadores": 1,
        "Apuração de ponto": 1,
        "Plano de saúde": 1,
        "Cálculos": 1,
        "Relatórios e recibos": 0.25,
        "e-Social": 2,
        "Auditor e-Social": 0.25,
        "Módulo SST": 0.25,
        "SChIp": 0.25,
        "SEFIP e DARF IR": 0.25,
        "Exportação para Sucessor": 0.25,
        "Utilitários e opções de segurança": 0.25,
    },
    "fiscal": {
        "Configurações declarações ": 0.25,
        "Inconsistências": 1,
        "Plano de troca global": 1,
        "Plano de configurações do simples": 1,
        "Planos estaduais ": 1,
        "Schip fiscal": 1,
        "Importação de Notas Fiscais": 2,
        "Operações imobiliárias": 0.25,
        "Apuração dos impostos": 1,
        "Impostos e relatórios": 1,
        "Declarações": 1,
        "Auditor valores portais estaduais": 0.25,
        "Auditor Connection IAT": 1,
        "Auditor REINF": 0.25,
    },
    "contábil": {
        "Configurações de contabilização": 0.5,
        "Plano de Contas": 0.25,
        "Plano de Centro de Custo": 0.25,
        "Plano de/para": 0.5,
        "Plano de Programas": 0.25,
        "Produtor Rural": 0.5,
        "Carnê Leão": 0.5,
        "IBGE": 0.5,
        "Distribuição de Lucros": 0.25,
        "Lançamentos Automáticos SCHIP": 0.25,
        "Conciliações": 0.25,
        "Importação de Saldos": 1,
        "Importação de Extratos": 0.25,
        "SPED ECD/ECF": 0.5,
        "S-sfinge Tribunal de Contas SC": 0.25,
        "Relatórios": 0.25,
        "Auditor ECD": 0.25,
        "Auditor ECF": 0.25,
        "NV Patrimônio": 0.5,
        "NV Lalur": 0.75,

    },
    "financeiro": {
        "Central de Contas a Receber": 0.5,
        "Central de Contas a Pagar": 0.5,
        "Relatórios": 0.5,
    },
    "tarefas": {
        "Plano tributário": 0.5,
        "Configuração de tarefas": 0.5,
        "Central de tarefas": 0.5,
        "Lançamentos de tarefas": 0.25,
        "Relatórios": 0.25,
    },
    "protocolos": {
        "Consulta e emissão de protocolos" : 1,
    },
    "notificações": {
       "Configurações de usuários": 0.25,
       "Configuração de empresas":  0.25,
       "Detalhamento dos módulos":  0.25,
    },
    "impostos": {
        "Calculo geral de Impostos": 0.25,
        "Envio para SCI Report": 0.25,
        "Calculo de Juros e Multa Geral": 0.25,
        "Funcionalidades": 0.25,
    },
    "tecweb": {
        "Push SCI 2.0": 0.5,
        "Instalação Push": 0.5,
        "ISS Legal SCI": 0.5,
        "RH NET Social": 1,
        "Integra NET": 0.5,
        "SBS - Smart Bank Statement": 0.75,
        "SCI Report - Serviços 24H": 1,
        // "SCI Report - Tarefas": 1,
        "SCI Report - Atendimento": 0.5,
        "SCI Report - CND": 0.5,
        "Dasboard SCI": 0.25,
        "SCI Print PDF": 0.25,
        "Agente SCI": 0.25,
        "SCI App 4.0": 0.5,
    },
}